language: node_js
dist: xenial
node_js:
  - "11"
env:
  - GCC_VERSION="export CC=gcc-7 && export CXX=g++-7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libhdf5-dev
before_install:
  - printf '{"username":"fj","password":"fjkd"}' > /tmp/config.json
  - g++ --version
  - export CXX=/usr/bin/g++-7
  - which g++-7
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60  --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - which g++ 
  - echo $PATH
  - export PATH="/usr/local/bin:$PATH"
  - g++ --version
  - ls /usr/lib/x86_64-linux-gnu/hdf5/serial
  - npm install hdf5 --hdf5_home_linux=/usr/lib/x86_64-linux-gnu/hdf5/serial
script:
  - npm test 
after_success:
  - codecov
