language: node_js
dist: xenial
node_js:
  - "11"
env:
  - GCC_VERSION="export CXX=/usr/bin/g++-7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libhdf5-dev
before_install:
  - printf '{"username":"fj","password":"fjkd"}' > /tmp/config.json
  - g++ --version
  - sudo apt-get remove g++
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60  --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - which g++ 
  - /usr/bin/g++ --version
  - g++ --version
  - ls /usr/lib/x86_64-linux-gnu/hdf5/serial
  - env CXX=/usr/bin/g++-7 npm install hdf5 --hdf5_home_linux=/usr/lib/x86_64-linux-gnu/hdf5/serial
script:
  - npm test 
after_success:
  - codecov
