language: node_js
dist: xenial
node_js:
  - "8"
  - "9"
  - "10"
env:
  - CODACY_PROJECT_TOKEN ="lTbP7Sp77jutsccIL2GyzUzYweHv4nf5K"
  - CODECOV_TOKEN =":c644c860-2927-4051-a512-5f2efa323601"
env:
  - GCC_VERSION="export CC=gcc-7 && export CXX=g++-7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libhdf5-dev
script:
  - printf '{"username":"fj","password":"fjkd"}' > /tmp/config.json
  - yarn global add codecov
  - yarn config set hdf5_home_linux /usr/lib/x86_64-linux-gnu/hdf5/serial
  - yarn
  - yarn run mocha -r ts-node/register test/*.ts --exit
  - yarn 
after_success:
  - codecov
