language: node_js
dist: xenial
node_js:
  - "8"
  - "9"
  - "10"
env:
  - CODACY_PROJECT_TOKEN ="lTbP7Sp77jutsccIL2GyzUzYweHv4nf5K"
  - CODECOV_TOKEN =":c644c860-2927-4051-a512-5f2efa323601"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libhdf5-dev
script:
  - printf '{"username":"fj","password":"fjkd"}' > /tmp/config.json
  - yarn global add codecov
  - yarn run mocha -r ts-node/register test/*.ts --exit
  - yarn 
after_success:
  - codecov
