language: node_js
dist: xenial
node_js:
  - "10"
  - "11"
env:
  - CODACY_PROJECT_TOKEN ="lTbP7Sp77jutsccIL2GyzUzYweHv4nf5K"
  - CODECOV_TOKEN =":c644c860-2927-4051-a512-5f2efa323601"
  - GCC_VERSION="export CC=gcc-7 && export CXX=g++-7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libhdf5-dev
script:
  - printf '{"username":"fj","password":"fjkd"}' > /tmp/config.json
  - g++ --version
  - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60  --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - g++ --version
  - ls /usr/lib/x86_64-linux-gnu/hdf5/serial
  - npm install hdf5 --hdf5_home_linux=/usr/lib/x86_64-linux-gnu/hdf5/serial
  - npm  install hdf5
  - npm test 
after_success:
  - codecov
