export class BeamInstrumentationMetadata {
  metadata_object: Object;
  sourceFolderArray: Object;

  constructor() {
    this.metadata_object = {
      "0001": { 
          'tag0000':'/BW_measurement',
          'tag0001':'/BW_measurement/WFG',
          'tag0002':'/BW_measurement/WFG/100KHz_1.8V',
          'tag0003':'/BW_measurement/WFG/10MHz_1.8V',
          'tag0004':'/BW_measurement/WFG/1MHz_1.8V',
          'tag0005':'/BW_measurement/WFG/200KHz_1.8V',
          'tag0006':'/BW_measurement/WFG/20MHz_1.8V',
          'tag0007':'/BW_measurement/WFG/2MHz_1.8V',
          'tag0008':'/BW_measurement/WFG/300KHz_1.8V',
          'tag0009':'/BW_measurement/WFG/30MHz_1.8V',
          'tag0010':'/BW_measurement/WFG/3MHz_1.8V',
          'tag0011':'/BW_measurement/WFG/400KHz_1.8V',
          'tag0012':'/BW_measurement/WFG/40MHz_1.8V',
          'tag0013':'/BW_measurement/WFG/4MHz_1.8V',
          'tag0014':'/BW_measurement/WFG/500KHz_1.8V',
          'tag0015':'/BW_measurement/WFG/50MHz_1.8V',
          'tag0016':'/BW_measurement/WFG/5MHz_1.8V',
          'tag0017':'/BW_measurement/WFG/600KHz_1.8V',
          'tag0018':'/BW_measurement/WFG/6MHz_1.8V',
          'tag0019':'/BW_measurement/WFG/700KHz_1.8V',
          'tag0020':'/BW_measurement/WFG/7MHz_1.8V',
          'tag0021':'/BW_measurement/WFG/800KHz_1.8V',
          'tag0022':'/BW_measurement/WFG/8MHz_1.8V',
          'tag0023':'/BW_measurement/WFG/900KHz_1.8V',
          'tag0024':'/BW_measurement/WFG/9MHz_1.8V',
          'tag0025':'/Background_noise',
          'tag0026':'/Background_noise_keithley',
          'tag0027':'/Linearity_measurement',
          'tag0028':'/Linearity_measurement/current_source',
          'tag0029':'/Linearity_measurement/current_source/Current_source_0mA',
          'tag0030':'/Linearity_measurement/current_source/Current_source_100mA',
          'tag0031':'/Linearity_measurement/current_source/Current_source_10mA',
          'tag0032':'/Linearity_measurement/current_source/Current_source_20mA',
          'tag0033':'/Linearity_measurement/current_source/Current_source_30mA',
          'tag0034':'/Linearity_measurement/current_source/Current_source_40mA',
          'tag0035':'/Linearity_measurement/current_source/Current_source_50mA',
          'tag0036':'/Linearity_measurement/current_source/Current_source_60mA',
          'tag0037':'/Linearity_measurement/current_source/Current_source_70mA',
          'tag0038':'/Linearity_measurement/current_source/Current_source_80mA',
          'tag0039':'/Linearity_measurement/current_source/Current_source_90mA',
          'tag0040':'/Noise_measurment/current_source',
          'tag0041':'/Pulse_measurement',
          'tag0042':'/Pulse_measurement/current_source',
          'tag0043':'/Pulse_measurement/current_source/Current_source_100mA_100KHz',
          'tag0044':'/Pulse_measurement/current_source/Current_source_10mA_100KHz',
          'tag0045':'/Pulse_measurement/current_source/Current_source_1mA_100KHz',
          'tag0046':'/Pulse_measurement/current_source/Current_source_1mA_10KHz',
          'tag0047':'/Pulse_measurement/current_source/Current_source_20mA_100KHz',
          'tag0048':'/Pulse_measurement/current_source/Current_source_30mA_100KHz',
          'tag0049':'/Pulse_measurement/current_source/Current_source_40mA_100KHz',
          'tag0050':'/Pulse_measurement/current_source/Current_source_50mA_100KHz',
          'tag0051':'/Pulse_measurement/current_source/Current_source_60mA_100KHz',
          'tag0052':'/Pulse_measurement/current_source/Current_source_70mA_100KHz',
          'tag0053':'/Pulse_measurement/current_source/Current_source_80mA_100KHz',
          'tag0054':'/Pulse_measurement/current_source/Current_source_90mA_100KHz'
         },
      "0002": { 
          'tag000':'/BW_measurement',
          'tag001':'/BW_measurement/WFG',
          'tag002':'/BW_measurement/WFG/1MSPS_1mARange_VITA_100KHz',
          'tag003':'/BW_measurement/WFG/1MSPS_1mARange_VITA_100Khz_noBiasTee',
          'tag004':'/BW_measurement/WFG/1MSPS_1mARange_VITA_10KHz',
          'tag005':'/BW_measurement/WFG/1MSPS_1mARange_VITA_10Khz_noBiasTee',
          'tag006':'/BW_measurement/WFG/1MSPS_1mARange_VITA_150KHz',
          'tag007':'/BW_measurement/WFG/1MSPS_1mARange_VITA_150Khz_noBiasTee',
          'tag008':'/BW_measurement/WFG/1MSPS_1mARange_VITA_15KHz',
          'tag009':'/BW_measurement/WFG/1MSPS_1mARange_VITA_1KHz',
          'tag010':'/BW_measurement/WFG/1MSPS_1mARange_VITA_1Khz_noBiasTee',
          'tag011':'/BW_measurement/WFG/1MSPS_1mARange_VITA_20KHz',
          'tag012':'/BW_measurement/WFG/1MSPS_1mARange_VITA_20Khz_noBiasTee',
          'tag013':'/BW_measurement/WFG/1MSPS_1mARange_VITA_25KHz',
          'tag014':'/BW_measurement/WFG/1MSPS_1mARange_VITA_2KHz',
          'tag015':'/BW_measurement/WFG/1MSPS_1mARange_VITA_2Khz_noBiasTee',
          'tag016':'/BW_measurement/WFG/1MSPS_1mARange_VITA_30KHz',
          'tag017':'/BW_measurement/WFG/1MSPS_1mARange_VITA_30Khz_noBiasTee',
          'tag018':'/BW_measurement/WFG/1MSPS_1mARange_VITA_3KHz',
          'tag019':'/BW_measurement/WFG/1MSPS_1mARange_VITA_3Khz_noBiasTee',
          'tag020':'/BW_measurement/WFG/1MSPS_1mARange_VITA_40KHz',
          'tag021':'/BW_measurement/WFG/1MSPS_1mARange_VITA_40Khz_noBiasTee',
          'tag022':'/BW_measurement/WFG/1MSPS_1mARange_VITA_4KHz',
          'tag023':'/BW_measurement/WFG/1MSPS_1mARange_VITA_4Khz_noBiasTee',
          'tag024':'/BW_measurement/WFG/1MSPS_1mARange_VITA_50KHz',
          'tag025':'/BW_measurement/WFG/1MSPS_1mARange_VITA_50Khz_noBiasTee',
          'tag026':'/BW_measurement/WFG/1MSPS_1mARange_VITA_5KHz',
          'tag027':'/BW_measurement/WFG/1MSPS_1mARange_VITA_5Khz_noBiasTee',
          'tag028':'/BW_measurement/WFG/1MSPS_1mARange_VITA_60KHz',
          'tag029':'/BW_measurement/WFG/1MSPS_1mARange_VITA_60Khz_noBiasTee',
          'tag030':'/BW_measurement/WFG/1MSPS_1mARange_VITA_6KHz',
          'tag031':'/BW_measurement/WFG/1MSPS_1mARange_VITA_6Khz_noBiasTee',
          'tag032':'/BW_measurement/WFG/1MSPS_1mARange_VITA_70Khz_noBiasTee',
          'tag034':'/BW_measurement/WFG/1MSPS_1mARange_VITA_7KHz',
          'tag035':'/BW_measurement/WFG/1MSPS_1mARange_VITA_7Khz_noBiasTee',
          'tag036':'/BW_measurement/WFG/1MSPS_1mARange_VITA_80KHz',
          'tag037':'/BW_measurement/WFG/1MSPS_1mARange_VITA_80Khz_noBiasTee',
          'tag038':'/BW_measurement/WFG/1MSPS_1mARange_VITA_8KHz',
          'tag039':'/BW_measurement/WFG/1MSPS_1mARange_VITA_8Khz_noBiasTee',
          'tag040':'/BW_measurement/WFG/1MSPS_1mARange_VITA_90Khz_noBiasTee',
          'tag041':'/BW_measurement/WFG/1MSPS_1mARange_VITA_9KHz',
          'tag042':'/BW_measurement/WFG/1MSPS_1mARange_VITA_9Khz_noBiasTee',
          'tag043':'/BW_measurement/WFG/Thorlabs',
          'tag044':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_100Khz',
          'tag045':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_10Khz',
          'tag046':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_150Khz',
          'tag047':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_15Khz',
          'tag048':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_1Khz',
          'tag049':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_20Khz',
          'tag050':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_2Khz',
          'tag051':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_30Khz',
          'tag053':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_3Khz',
          'tag054':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_40Khz',
          'tag055':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_4Khz',
          'tag056':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_50Khz',
          'tag057':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_5Khz',
          'tag058':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_60Khz',
          'tag059':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_6Khz',
          'tag060':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_7Khz',
          'tag061':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_80Khz',
          'tag062':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_8Khz',
          'tag063':'/BW_measurement/WFG/Thorlabs/1MSPS_1mARange_VITA_9Khz'
        },
      "0003": {
        
      }
    };
    this.sourceFolderArray = {
      "0001": "beamInstrumentation/bandwidth",
      "0002": "beamInstrumentation/tee",
      "0003": "beamInstrumentation/FMC-PICO-evaluation"
    };
  }
}
